-- MySQL Script generated by MySQL Workbench
-- Wed Jun  8 21:37:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema OCPizzaDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OCPizzaDB` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `OCPizzaDB` ;

-- -----------------------------------------------------
-- Table `OCPizzaDB`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizzaDB`.`Address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `streetNumber` VARCHAR(15) NOT NULL,
  `streetName` VARCHAR(100) NOT NULL,
  `additional` VARCHAR(100) NULL DEFAULT NULL,
  `zipCode` VARCHAR(15) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `country` VARCHAR(100) NOT NULL,
  `comments` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `OCPizzaDB`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizzaDB`.`Customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(15) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `OCPizzaDB`.`Restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizzaDB`.`Restaurant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `Address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Restaurant_Address1_idx` (`Address_id` ASC) VISIBLE,
  CONSTRAINT `fk_Restaurant_Address1`
    FOREIGN KEY (`Address_id`)
    REFERENCES `OCPizzaDB`.`Address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `OCPizzaDB`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizzaDB`.`Order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `timestamp` TIMESTAMP(3) NOT NULL,
  `status` ENUM("pending", "cancelled", "processing", "prepared", "readyForPickUp_Paid", "readyForPickUp_NotPaid", "waitingForDelivery", "beingDelivered", "delivered", "refused") NOT NULL,
  `deliveryMethod` ENUM("onSite", "HomeDelivery") NOT NULL,
  `paymentMethod` ENUM("online_creditCard", "online_paypal", "onsite_creditCard", "onsite_meal_voucher", "onsite_cash") NOT NULL,
  `isPaid` TINYINT NOT NULL,
  `Customer_id` INT NOT NULL,
  `Restaurant_id` INT NOT NULL,
  `Address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Order_Customer1_idx` (`Customer_id` ASC) VISIBLE,
  INDEX `fk_Order_Restaurant1_idx` (`Restaurant_id` ASC) VISIBLE,
  INDEX `fk_Order_Address1_idx` (`Address_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Customer1`
    FOREIGN KEY (`Customer_id`)
    REFERENCES `OCPizzaDB`.`Customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Restaurant1`
    FOREIGN KEY (`Restaurant_id`)
    REFERENCES `OCPizzaDB`.`Restaurant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Address1`
    FOREIGN KEY (`Address_id`)
    REFERENCES `OCPizzaDB`.`Address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `OCPizzaDB`.`Billing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizzaDB`.`Billing` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(6,2) NOT NULL,
  `Order_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Billing_Order1_idx` (`Order_id` ASC) VISIBLE,
  CONSTRAINT `fk_Billing_Order1`
    FOREIGN KEY (`Order_id`)
    REFERENCES `OCPizzaDB`.`Order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `OCPizzaDB`.`InventorySystem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizzaDB`.`InventorySystem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Restaurant_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_InventorySystem_Restaurant1_idx` (`Restaurant_id` ASC) VISIBLE,
  CONSTRAINT `fk_InventorySystem_Restaurant1`
    FOREIGN KEY (`Restaurant_id`)
    REFERENCES `OCPizzaDB`.`Restaurant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `OCPizzaDB`.`Stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizzaDB`.`Stock` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `quantity` DECIMAL(6,2) NULL DEFAULT NULL,
  `unit` VARCHAR(15) NOT NULL,
  `InventorySystem_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Stock_InventorySystem1_idx` (`InventorySystem_id` ASC) VISIBLE,
  CONSTRAINT `fk_Stock_InventorySystem1`
    FOREIGN KEY (`InventorySystem_id`)
    REFERENCES `OCPizzaDB`.`InventorySystem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `OCPizzaDB`.`Ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizzaDB`.`Ingredient` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `unit` VARCHAR(15) NOT NULL,
  `Stock_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Ingredient_Stock1_idx` (`Stock_id` ASC) VISIBLE,
  CONSTRAINT `fk_Ingredient_Stock1`
    FOREIGN KEY (`Stock_id`)
    REFERENCES `OCPizzaDB`.`Stock` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `OCPizzaDB`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizzaDB`.`Item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `price` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `OCPizzaDB`.`RestaurantMenu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizzaDB`.`RestaurantMenu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Restaurant_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_RestaurantMenu_Restaurant1_idx` (`Restaurant_id` ASC) VISIBLE,
  CONSTRAINT `fk_RestaurantMenu_Restaurant1`
    FOREIGN KEY (`Restaurant_id`)
    REFERENCES `OCPizzaDB`.`Restaurant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `OCPizzaDB`.`Recipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizzaDB`.`Recipe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `instructions` VARCHAR(600) NOT NULL,
  `Item_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Recipe_Item1_idx` (`Item_id` ASC) VISIBLE,
  CONSTRAINT `fk_Recipe_Item1`
    FOREIGN KEY (`Item_id`)
    REFERENCES `OCPizzaDB`.`Item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `OCPizzaDB`.`OpeningHours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizzaDB`.`OpeningHours` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `day` ENUM("monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday") NOT NULL,
  `openingHour` TIME NOT NULL,
  `closingHour` TIME NOT NULL,
  `isOpen` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `OCPizzaDB`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizzaDB`.`Staff` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(15) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `position` ENUM("host", "chef", "deliveryMan", "Admin") NOT NULL,
  `Restaurant_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Staff_Restaurant1_idx` (`Restaurant_id` ASC) VISIBLE,
  CONSTRAINT `fk_Staff_Restaurant1`
    FOREIGN KEY (`Restaurant_id`)
    REFERENCES `OCPizzaDB`.`Restaurant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;




-- -----------------------------------------------------
-- Table `OCPizzaDB`.`Order_has_Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizzaDB`.`Order_has_Item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Order_id` INT NOT NULL,
  `Item_id` INT NOT NULL,
  `quantity` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_table1_Item1_idx` (`Item_id` ASC) VISIBLE,
  CONSTRAINT `fk_table1_Order1`
    FOREIGN KEY (`Order_id`)
    REFERENCES `OCPizzaDB`.`Order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_Item1`
    FOREIGN KEY (`Item_id`)
    REFERENCES `OCPizzaDB`.`Item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OCPizzaDB`.`Recipe_has_Ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizzaDB`.`Recipe_has_Ingredient` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Recipe_id` INT NOT NULL,
  `Ingredient_id` INT NOT NULL,
  `amount` DECIMAL(6,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_RecipeIngredient_Ingredient1_idx` (`Ingredient_id` ASC) VISIBLE,
  CONSTRAINT `fk_RecipeIngredient_Recipe1`
    FOREIGN KEY (`Recipe_id`)
    REFERENCES `OCPizzaDB`.`Recipe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RecipeIngredient_Ingredient1`
    FOREIGN KEY (`Ingredient_id`)
    REFERENCES `OCPizzaDB`.`Ingredient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OCPizzaDB`.`RestaurantMenu_has_Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizzaDB`.`RestaurantMenu_has_Item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `RestaurantMenu_id` INT NOT NULL,
  `Item_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_RestaurantMenuItem_Item1_idx` (`Item_id` ASC) VISIBLE,
  CONSTRAINT `fk_RestaurantMenuItem_RestaurantMenu1`
    FOREIGN KEY (`RestaurantMenu_id`)
    REFERENCES `OCPizzaDB`.`RestaurantMenu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RestaurantMenuItem_Item1`
    FOREIGN KEY (`Item_id`)
    REFERENCES `OCPizzaDB`.`Item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OCPizzaDB`.`Customer_has_Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizzaDB`.`Customer_has_Address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Customer_id` INT NOT NULL,
  `Address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Customer_has_Address_Address1_idx` (`Address_id` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_has_Address_Customer1`
    FOREIGN KEY (`Customer_id`)
    REFERENCES `OCPizzaDB`.`Customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customer_has_Address_Address1`
    FOREIGN KEY (`Address_id`)
    REFERENCES `OCPizzaDB`.`Address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `OCPizzaDB`.`Restaurant_has_OpeningHours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizzaDB`.`Restaurant_has_OpeningHours` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Restaurant_id` INT NOT NULL,
  `OpeningHours_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Restaurant_has_OpeningHours_OpeningHours1_idx` (`OpeningHours_id` ASC) VISIBLE,
  INDEX `fk_Restaurant_has_OpeningHours_Restaurant1_idx` (`Restaurant_id` ASC) VISIBLE,
  CONSTRAINT `fk_Restaurant_has_OpeningHours_Restaurant1`
    FOREIGN KEY (`Restaurant_id`)
    REFERENCES `OCPizzaDB`.`Restaurant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Restaurant_has_OpeningHours_OpeningHours1`
    FOREIGN KEY (`OpeningHours_id`)
    REFERENCES `OCPizzaDB`.`OpeningHours` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
